import type { MachineProfile } from "./profile.js";
import { BLOCKED } from "./guard.js";

export type Severity = "error" | "warning" | "info";
export interface Finding { severity: Severity; code: string; message: string; line?: number }

export interface PreflightOptions {
  profile?: MachineProfile;
  maxTemp?: { bed: number; tool: number };
  nozzle?: number; // nozzle diameter in mm, used to judge the line width
  filamentDiameter?: number; // default 1.75
}

export interface Report {
  verdict: "ok" | "warnings" | "errors";
  findings: Finding[];
  summary: {
    lines: number;
    flavor?: string;
    slicer?: string;
    extents?: { x: [number, number]; y: [number, number]; z: [number, number] };
    maxToolTemp: number;
    maxBedTemp: number;
    maxFanPercent: number;
    layerHeight?: number;
    estLineWidth?: number;
    filamentMeters: number;
    filamentGrams: number;
    timeSeconds?: number;
    timeSource?: "slicer" | "rough estimate";
    firstExtrusionLine?: number;
    firstHeaterLine?: number;
    g28Lines: number[];
    needsToolSelect: boolean;
  };
}

// Firmware / network / credential / file-deletion commands: must never be in a print file.
const DANGEROUS = /^(M997|M552|M587|M589|M551|M28|M29|M30)$/;
const num = (v: string | undefined) => (v === undefined ? undefined : Number(v));
const median = (a: number[]) => { const s = [...a].sort((x, y) => x - y); return s[Math.floor(s.length / 2)]; };

export function analyzeGcode(text: string, opt: PreflightOptions = {}): Report {
  const findings: Finding[] = [];
  const add = (severity: Severity, code: string, message: string, line?: number) => findings.push({ severity, code, message, line });
  const lines = text.split(/\r?\n/);
  const limits = opt.profile?.axisLimits ?? {};
  const fil = opt.filamentDiameter ?? 1.75;
  const area = Math.PI * (fil / 2) ** 2;

  let flavor: string | undefined, slicer: string | undefined, headerTime: number | undefined, headerLayer: number | undefined, headerFilamentM: number | undefined;
  const pos: Record<string, number | undefined> = {};
  let relative = false, relE = false, e = 0;
  let toolSelected = false, needsToolSelect = false, needToolLine: number | undefined;
  let maxTool = 0, maxBed = 0, maxFan = 0;
  let hotSet = false, hotWait = false, bedSet = false;
  let firstExt: number | undefined, firstHeater: number | undefined, lastExtLine = 0;
  let toolOffSince = false, bedOffSince = false;
  const g28: number[] = [];
  const ext = { xmin: Infinity, xmax: -Infinity, ymin: Infinity, ymax: -Infinity, zmin: Infinity, zmax: -Infinity };
  const perZ = new Map<number, { len: number; de: number }>();
  let totalE = 0, roughSec = 0, extrudedMoves = 0;
  const oob: Record<string, { line: number; value: number } | undefined> = {};
  const seenBlocked = new Set<string>();
  const marlinOnly = new Set<string>();

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const ln = i + 1;
    const ci = raw.indexOf(";");
    if (ci >= 0 && i < 80) {
      const c = raw.slice(ci + 1).trim();
      let m: RegExpMatchArray | null;
      if ((m = c.match(/^FLAVOR:(.+)/))) flavor = m[1];
      else if ((m = c.match(/^TIME:(\d+)/))) headerTime = +m[1];
      else if ((m = c.match(/^Layer height:\s*([\d.]+)/i))) headerLayer = +m[1];
      else if ((m = c.match(/^Filament used:\s*([\d.]+)\s*m/i))) headerFilamentM = +m[1];
      else if ((m = c.match(/^Generated with (.+)/i))) slicer = m[1];
      else if ((m = c.match(/^generated by (.+?) on/i))) slicer = m[1];
    }
    const code = (ci >= 0 ? raw.slice(0, ci) : raw).trim();
    if (!code) continue;
    const head = code.match(/^([GMT])\s*(-?\d+)(?:\.\d+)?/i);
    if (!head) continue;
    const letter = head[1].toUpperCase();
    const n = parseInt(head[2], 10);
    const word = `${letter}${n}`;
    const rest = code.slice(head[0].length);
    const p: Record<string, number> = {};
    for (const m of rest.matchAll(/([A-Za-z])\s*(-?\d*\.?\d+)/g)) p[m[1].toUpperCase()] = +m[2];

    if (letter === "T") { if (n >= 0) toolSelected = true; continue; }

    if (BLOCKED.test(word)) {
      if (!seenBlocked.has(word)) {
        seenBlocked.add(word);
        add(DANGEROUS.test(word) ? "error" : "warning", "blocked-command", `${word} in a print file changes firmware/network/limits/config. It is blocked in send_gcode and should not be in a print file.`, ln);
      }
    }
    if (/^M(900|420|413)$/.test(word) && !marlinOnly.has(word)) {
      marlinOnly.add(word);
      add("info", "marlin-only", `${word} is Marlin-specific; RepRapFirmware ignores or rejects it (linear advance on Duet is M572).`, ln);
    }

    if (word === "G90") relative = false;
    else if (word === "G91") relative = true;
    else if (word === "M82") relE = false;
    else if (word === "M83") relE = true;
    else if (word === "G92") {
      for (const a of ["X", "Y", "Z"]) if (p[a] !== undefined) pos[a] = p[a];
      if (p.E !== undefined) e = p.E;
    } else if (word === "G28") g28.push(ln);
    else if (word === "M104" || word === "M109" || word === "G10") {
      const s = word === "G10" ? p.S : p.S;
      if (s !== undefined) {
        maxTool = Math.max(maxTool, s);
        if (firstHeater === undefined && word !== "G10") firstHeater = ln;
        if (s > 0 && word !== "G10") { hotSet = true; if (p.T === undefined && !toolSelected) { needsToolSelect = true; needToolLine ??= ln; } }
        if (word === "M109" && s > 0) hotWait = true;
        if (s <= 0 && word === "M104") toolOffSince = true;
      }
    } else if (word === "M116") hotWait = true;
    else if (word === "M140" || word === "M190") {
      if (p.S !== undefined) {
        maxBed = Math.max(maxBed, p.S);
        if (firstHeater === undefined) firstHeater = ln;
        if (p.S > 0) bedSet = true; else bedOffSince = true;
      }
    } else if (word === "M106") {
      if (p.S !== undefined) maxFan = Math.max(maxFan, p.S <= 1 ? p.S : p.S / 255);
    } else if (word === "G0" || word === "G1" || word === "G2" || word === "G3") {
      const prev = { x: pos.X, y: pos.Y, z: pos.Z };
      for (const a of ["X", "Y", "Z"]) {
        if (p[a] === undefined) continue;
        if (relative) { if (pos[a] !== undefined) pos[a] = pos[a]! + p[a]; }
        else {
          pos[a] = p[a];
          const lim = limits[a];
          if (p.H === undefined && lim && ((lim.min !== undefined && p[a] < lim.min - 0.01) || (lim.max !== undefined && p[a] > lim.max + 0.01))) {
            oob[a] ??= { line: ln, value: p[a] };
          }
        }
      }
      let dE = 0;
      if (p.E !== undefined) {
        if (relE) { dE = p.E; e += p.E; } else { dE = p.E - e; e = p.E; }
      }
      const len = prev.x !== undefined && prev.y !== undefined && pos.X !== undefined && pos.Y !== undefined ? Math.hypot(pos.X - prev.x, pos.Y - prev.y) : 0;
      if (p.F && len > 0) roughSec += len / (p.F / 60);
      if (word !== "G0" && dE > 0 && (len > 0 || p.Z !== undefined || pos.X !== undefined)) {
        if (firstExt === undefined) {
          firstExt = ln;
          if (!hotSet) add("error", "no-heat-before-extrusion", "The first extruding move comes before any nozzle heating command (M104/M109).", ln);
          else if (!hotWait) add("warning", "no-wait-for-heat", "The nozzle is heated with M104 but nothing waits for the temperature (M109/M116) before the first extrusion.", ln);
        }
        lastExtLine = ln; toolOffSince = false; bedOffSince = false;
        extrudedMoves++;
        for (const [a, v] of [["x", pos.X], ["y", pos.Y], ["x", prev.x], ["y", prev.y]] as const) {
          if (v === undefined) continue;
          if (a === "x") { ext.xmin = Math.min(ext.xmin, v); ext.xmax = Math.max(ext.xmax, v); } else { ext.ymin = Math.min(ext.ymin, v); ext.ymax = Math.max(ext.ymax, v); }
        }
        if (pos.Z !== undefined) { ext.zmin = Math.min(ext.zmin, pos.Z); ext.zmax = Math.max(ext.zmax, pos.Z); }
        totalE += dE;
        if (len > 0.3 && pos.Z !== undefined) {
          const k = Math.round(pos.Z * 1000) / 1000;
          const a = perZ.get(k) ?? { len: 0, de: 0 };
          a.len += len; a.de += dE; perZ.set(k, a);
        }
      }
    }
  }

  // --- findings from collected state
  for (const [a, o] of Object.entries(oob)) {
    if (o) add("error", "out-of-bounds", `Move to ${a}${o.value} is outside the machine limits ${limits[a]?.min ?? "-"}..${limits[a]?.max ?? "-"} (first at this line). The firmware would stop the job.`, o.line);
  }
  const tl = opt.maxTemp?.tool, bl = opt.maxTemp?.bed;
  if (tl !== undefined && maxTool > tl) add("error", "over-temp", `Nozzle target ${maxTool} C exceeds the configured limit of ${tl} C.`);
  if (bl !== undefined && maxBed > bl) add("error", "over-temp", `Bed target ${maxBed} C exceeds the configured limit of ${bl} C.`);
  if (firstExt === undefined) add("error", "no-extrusion", "The file contains no extruding moves.");
  if (needsToolSelect) add("warning", "no-tool-select", "M104/M109 without a T parameter and no tool selected (T0) before it: on a Duet this fails when no tool is active, the nozzle would stay cold. Fix: select-tool.", needToolLine);
  const startG28 = g28.filter((l) => firstExt === undefined || l < firstExt);
  if (startG28.length) add("warning", "g28-in-start", "G28 in the start block runs homeall.g, which does not back off from an endstop that is already pressed. Home with home_axes first (start_job requires it) and drop it with fix strip-g28.", startG28[0]);
  if (firstExt !== undefined && lastExtLine && !(toolOffSince && (bedOffSince || !bedSet))) {
    add("warning", "heaters-stay-on", "No M104 S0 / M140 S0 after the last extruding move: the heaters would stay on after the print (the idle watchdog would catch it after a while).");
  }

  // layer height and line width
  const zs = [...perZ.keys()].sort((a, b) => a - b);
  let layerHeight = headerLayer;
  if (layerHeight === undefined && zs.length > 2) layerHeight = median(zs.slice(1).map((z, i) => z - zs[i]).filter((d) => d > 0.01));
  let estWidth: number | undefined;
  if (layerHeight) {
    const used = zs.length > 1 ? zs.slice(1) : zs;
    let sl = 0, sd = 0;
    for (const z of used) { const a = perZ.get(z)!; sl += a.len; sd += a.de; }
    if (sl > 0) estWidth = (sd / sl) * area / layerHeight;
  }
  if (estWidth !== undefined) {
    if (opt.nozzle) {
      const r = estWidth / opt.nozzle;
      if (r < 0.8 || r > 1.6) add("warning", "line-width", `Estimated line width ${estWidth.toFixed(2)} mm does not fit a ${opt.nozzle} mm nozzle (expected about ${(opt.nozzle * 0.9).toFixed(2)}-${(opt.nozzle * 1.4).toFixed(2)} mm). Wrong nozzle size in the slicer?`);
      else add("info", "line-width", `Estimated line width ${estWidth.toFixed(2)} mm fits a ${opt.nozzle} mm nozzle.`);
    } else add("info", "line-width", `Estimated line width ${estWidth.toFixed(2)} mm (assuming ${fil} mm filament). Pass nozzle=<mm> to check it.`);
  }
  if (maxFan > 0) add("info", "fan", `Maximum part fan ${(maxFan * 100).toFixed(0)} %.`);
  if (!bedSet && maxBed === 0) add("info", "no-bed-heat", "The file never heats the bed.");

  const meters = headerFilamentM ?? totalE / 1000;
  const errors = findings.some((f) => f.severity === "error");
  const warnings = findings.some((f) => f.severity === "warning");
  return {
    verdict: errors ? "errors" : warnings ? "warnings" : "ok",
    findings,
    summary: {
      lines: lines.length, flavor, slicer,
      extents: extrudedMoves ? { x: [ext.xmin, ext.xmax], y: [ext.ymin, ext.ymax], z: [ext.zmin, ext.zmax] } : undefined,
      maxToolTemp: maxTool, maxBedTemp: maxBed, maxFanPercent: Math.round(maxFan * 100),
      layerHeight, estLineWidth: estWidth === undefined ? undefined : Math.round(estWidth * 100) / 100,
      filamentMeters: Math.round(meters * 100) / 100,
      filamentGrams: Math.round(meters * 1000 * area / 1000 * 1.24 * 10) / 10,
      timeSeconds: headerTime ?? (roughSec > 0 ? Math.round(roughSec) : undefined),
      timeSource: headerTime !== undefined ? "slicer" : roughSec > 0 ? "rough estimate" : undefined,
      firstExtrusionLine: firstExt, firstHeaterLine: firstHeater, g28Lines: g28, needsToolSelect,
    },
  };
}

export type Fix = "select-tool" | "strip-g28";

/** Returns a patched copy of the text. Only touches the start block; the original is never modified. */
export function applyFixes(text: string, report: Report, fixes: Fix[]): { text: string; changes: string[] } {
  const eol = text.includes("\r\n") ? "\r\n" : "\n";
  const lines = text.split(/\r?\n/);
  const changes: string[] = [];
  const s = report.summary;
  if (fixes.includes("strip-g28") && s.firstExtrusionLine !== undefined) {
    for (const ln of s.g28Lines.filter((l) => l < s.firstExtrusionLine!)) {
      lines[ln - 1] = `;G28 removed by duet-mcp preflight (home with home_axes first): ${lines[ln - 1]}`;
      changes.push(`line ${ln}: G28 commented out`);
    }
  }
  const insertAt = fixes.includes("select-tool") && s.needsToolSelect ? s.firstHeaterLine : undefined;
  if (insertAt !== undefined) {
    lines.splice(insertAt - 1, 0, "T0 ;added by duet-mcp preflight: select tool 0 before heating");
    changes.push(`line ${insertAt}: T0 inserted`);
  }
  return { text: lines.join(eol), changes };
}

export function formatReport(r: Report, name = "G-code"): string {
  const s = r.summary;
  const out: string[] = [];
  out.push(`Preflight ${name}: ${r.verdict.toUpperCase()}`);
  if (s.slicer || s.flavor) out.push(`Slicer: ${s.slicer ?? "?"}${s.flavor ? ` (flavor ${s.flavor})` : ""}`);
  if (s.extents) out.push(`Print area: X ${s.extents.x[0].toFixed(1)}..${s.extents.x[1].toFixed(1)}, Y ${s.extents.y[0].toFixed(1)}..${s.extents.y[1].toFixed(1)}, Z ${s.extents.z[0].toFixed(2)}..${s.extents.z[1].toFixed(2)} mm`);
  out.push(`Temperatures: nozzle max ${s.maxToolTemp} C, bed max ${s.maxBedTemp} C${s.layerHeight ? `, layer height ${s.layerHeight} mm` : ""}`);
  out.push(`Filament: ${s.filamentMeters} m (about ${s.filamentGrams} g PLA)${s.timeSeconds !== undefined ? `, time ${Math.round(s.timeSeconds / 60)} min (${s.timeSource})` : ""}`);
  for (const sev of ["error", "warning", "info"] as const) {
    for (const f of r.findings.filter((x) => x.severity === sev)) out.push(`[${sev.toUpperCase()}] ${f.code}${f.line ? ` (line ${f.line})` : ""}: ${f.message}`);
  }
  return out.join("\n");
}
